version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: metadata
      POSTGRES_USER: metadata

  web:
    build: ./web
    ports:
      - "8101:8000"
    links:
      - database:database
    environment:
      DATABASE_NAME: metadata
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "atlas_meta.wsgi:application"