services:
  database:
    image: postgis/postgis:16-3.4
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: metadata
      POSTGRES_USER: metadata

  web:
    build: ./web
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./web/atlas_meta:/app
    environment:
      DATABASE_HOST_OVERRIDE: database
      DATABASE_NAME: metadata
      DATABASE_USER: metadata
      DATABASE_PASSWORD: insecure
    command: uwsgi --ini uwsgi.ini:dev
