# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaData",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True)),
                ("title", models.CharField(max_length=100, null=True)),
                ("group", models.CharField(max_length=100, null=True)),
                ("update_frequency", models.CharField(max_length=100, null=True)),
                ("data_modified_date", models.CharField(max_length=100, null=True)),
                ("last_import_date", models.DateField(null=True)),
            ],
        ),
    ]
