# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 12:18
from __future__ import unicode_literals

from django.db import migrations


data = [
    {
        'id': 'BAG',
        'title': 'BAG',
        'update_frequency': 'di. en vr.'
    },
    {
        'id': 'BRK',
        'title': 'BRK',
        'update_frequency': 'wekelijks'
    },
    {
        'id': 'Wkpb',
        'title': 'Wkpb',
        'update_frequency': 'dagelijks'
    },
    {
        'id': 'gebieden-stadsdeel',
        'title': 'Stadsdeel',
        'group': 'Gebieden',
        'update_frequency': 'op verzoek'
    },
    {
        'id': 'gebieden-buurtcombinatie',
        'title': 'Buurtcombinatie',
        'group': 'Gebieden',
        'update_frequency': 'op verzoek'
    },
    {
        'id': 'gebieden-buurtcombinatie',
        'title': 'Buurt',
        'group': 'Gebieden',
        'update_frequency': 'op verzoek'
    },
    {
        'id': 'gebieden-bouwblok',
        'title': 'Bouwblok',
        'group': 'Gebieden',
        'update_frequency': 'op verzoek'
    },
    {
        'id': 'gebieden-bouwblok',
        'title': 'Grootstedelijk gebied',
        'group': 'Gebieden',
        'update_frequency': 'op verzoek',
        'data_modified_date': '14 maart 2014',
    },
    {
        'id': 'gebieden-gebiedsgericht-werken',
        'title': 'Gebiedsgericht werken',
        'group': 'Gebieden',
        'update_frequency': 'op verzoek',
        'data_modified_date': '28 januari 2014',
    },
    {
        'id': 'gebieden-unesco-werelderfgoedgrens',
        'title': 'UNESCO werelderfgoedgrens',
        'group': 'Gebieden',
        'update_frequency': 'éénmalig',
        'data_modified_date': '1 augustus 2010',
    },
    {
        'id': 'AHN',
        'title': 'AHN',
        'update_frequency': '5-jaarlijks',
        'data_modified_date': '2014',
    },
    {
        'id': 'geodetische-infrastructuur',
        'title': 'Geodetische infrastructuur',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '2007',
    },
    {
        'id': 'luchtfotos',
        'title': 'Luchtfoto\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '1988 - 2015',
    },
    {
        'id': 'nap',
        'title': 'NAP',
        'group': 'NAP',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'jaarlijks',
    },
    {
        'id': 'meetbouten',
        'title': 'Meetbouten',
        'group': 'Meetbouten',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'jaarlijks',
    },
    {
        'id': 'panoramabeelden',
        'title': 'Panoramabeelden',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '1988 - 2015',
    },
    {
        'id': 'topografie-bgt',
        'group': 'Topografie',
        'title': 'BGT',
        'update_frequency': 'maandelijks',
    },
    {
        'id': 'topografie-KBKA10',
        'group': 'Topografie',
        'title': 'KBKA10',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'april 2012',
    },
    {
        'id': 'topografie-KBKA25',
        'group': 'Topografie',
        'title': 'KBKA25',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '1 april 2013',
    },
    {
        'id': 'topografie-KBKA50',
        'group': 'Topografie',
        'title': 'KBKA50',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'onbekend',
    },
    {
        'id': 'milieuthemas-bodeminformatie',
        'title': 'Bodeminformatie',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '15 februari 2012',
    },
    {
        'id': 'milieuthemas-lpg-stations',
        'title': 'LPG-stations',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '25 februari 2014',
    },
    {
        'id': 'milieuthemas-overige-risicovolle-bedrijven',
        'title': 'Overige risicovolle bedrijven',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '2015',
    },
    {
        'id': 'milieuthemas-risicozone-aardgasbuisleidingen',
        'title': 'Risicozone Aardgasbuisleidingen',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '11 mei 2011',
    },
    {
        'id': 'milieuthemas-risicozone-spoorwegen',
        'title': 'Risicozone Spoorwegen',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'maart 2015',
    },
    {
        'id': 'milieuthemas-risicozone-vaarwegen',
        'title': 'Risicozone Vaarwegen',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'maart 2015',
    },
    {
        'id': 'milieuthemas-risicozone-wegen',
        'title': 'Risicozone Wegen',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'maart 2015',
    },
    {
        'id': 'milieuthemas-veiligheidsafstanden-vuurwerk-en-munitieopslag',
        'title': 'Veiligheidsafstanden: Vuurwerk en munitieopslag',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'januari 2009',
    },
    {
        'id': 'milieuthemas-veiligheidsafstanden-gasdrukregel-en-meetstation',
        'title': 'Veiligheidsafstanden: Gasdrukregel en meetstation',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '2004',
    },
    {
        'id': 'milieuthemas-veiligheidsafstanden-sluis-wachtpl-bunkerschip',
        'title': 'Veiligheidsafstanden: Sluis, wachtpl, bunkerschip',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'maart 2009',
    },
    {
        'id': 'milieuthemas-planologische-geluidzone-spoorwegen',
        'title': 'Planologische geluidzone Spoorwegen',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'september 2005',
    },
    {
        'id': 'milieuthemas-vogelvrijwaringsgebied-schiphol',
        'title': 'Vogelvrijwaringsgebied Schiphol',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'oktober 2005',
    },
    {
        'id': 'milieuthemas-geluidzone-schiphol',
        'title': 'Geluidzone Schiphol',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': 'maart 2009',
    },
    {
        'id': 'milieuthemas-Hoogtebeperkende-vlakken-schiphol',
        'title': 'Hoogtebeperkende vlakken Schiphol',
        'group': 'Milieuthema\'s',
        'update_frequency': 'jaarlijks',
        'data_modified_date': '2004',
    },
    {
        'id': 'test-acc',
    },
    {
        'id': 'test-prod',
    },
]


def create_initial_data(apps, schema_editor):
    meta_model = apps.get_model('atlas', 'metadata')

    for model_data in data:
        model_data['id'] = model_data['id'].lower()
        m = meta_model(**model_data)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
