tests:
  build: ../web
  ports:
    - "5434:5432"
  links:
    - database:database
  environment:
    DATABASE_NAME: metadata
    DATABASE_PASSWORD: insecure
    METADATA_URL: ""
  command: bash -c "/app/docker-wait.sh && python manage.py test"

database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: metadata
    POSTGRES_USER: metadata
