version: '3.0'
services:
  tests:
    build: ../web
    ports:
      - "5434:5432"
    links:
      - database
    environment:
      DATABASE_NAME: metadata
      DATABASE_USER: metadata
      DATABASE_PASSWORD: insecure
      METADATA_URL: ""
    command: bash -c "/app/docker-wait.sh && python manage.py test"

  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: metadata
      POSTGRES_USER: metadata
